-- V2 (P5): tool registry (global catalog, not tenant-scoped) and the side-effect ledger (06 §4.8, §4.9).

CREATE TABLE tool_registry (
    tool_name          text PRIMARY KEY,
    version            integer     NOT NULL DEFAULT 1,
    description        text        NOT NULL,
    input_schema       jsonb       NOT NULL,
    output_schema      jsonb       NOT NULL,
    scopes             text[]      NOT NULL DEFAULT '{}',
    timeout_ms         integer     NOT NULL,
    retry              jsonb       NOT NULL,
    reversibility      text        NOT NULL,
    idempotency        text        NOT NULL,
    compensation_tool  text REFERENCES tool_registry (tool_name) DEFERRABLE INITIALLY DEFERRED,
    lookup             jsonb,
    dry_run_example    jsonb,
    CONSTRAINT tool_registry_version_chk CHECK (version > 0),
    CONSTRAINT tool_registry_timeout_chk CHECK (timeout_ms > 0),
    CONSTRAINT tool_registry_reversibility_chk CHECK (
        reversibility IN ('COMPENSATABLE', 'PIVOT', 'RETRIABLE', 'READ_ONLY')),
    CONSTRAINT tool_registry_idempotency_chk CHECK (idempotency IN ('NATIVE_KEY', 'LOOKUP', 'NONE')),
    -- Only compensatable tools have an inverse; a LOOKUP tool must say how to look the effect up.
    CONSTRAINT tool_registry_compensation_chk CHECK (
        (reversibility = 'COMPENSATABLE') = (compensation_tool IS NOT NULL)),
    CONSTRAINT tool_registry_lookup_chk CHECK (idempotency <> 'LOOKUP' OR lookup IS NOT NULL)
);

CREATE TABLE side_effect_ledger (
    effect_key        text PRIMARY KEY,
    tenant_id         text        NOT NULL REFERENCES tenant (id),
    execution_id      uuid        NOT NULL,
    node_id           text        NOT NULL,
    phase             text        NOT NULL,
    call_index        integer     NOT NULL,
    state             text        NOT NULL,
    idempotency_mode  text        NOT NULL,
    owner_attempt     integer     NOT NULL,
    lease_until       timestamptz NOT NULL,
    external_ref      text,
    response_ref      text,
    response          jsonb,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT side_effect_ledger_key_chk CHECK (effect_key ~ '^[0-9a-f]{64}$'),
    CONSTRAINT side_effect_ledger_phase_chk CHECK (phase IN ('FORWARD', 'COMPENSATE')),
    CONSTRAINT side_effect_ledger_state_chk CHECK (state IN ('PENDING', 'COMMITTED', 'UNKNOWN', 'FAILED')),
    CONSTRAINT side_effect_ledger_mode_chk CHECK (idempotency_mode IN ('NATIVE_KEY', 'LOOKUP', 'NONE')),
    CONSTRAINT side_effect_ledger_numbers_chk CHECK (call_index >= 0 AND owner_attempt >= 1),
    -- EffectKey is a hash of exactly these columns, so the natural key is unique too; its index also
    -- serves per-execution lookups (tenant_id, execution_id prefix).
    CONSTRAINT side_effect_ledger_natural_uq UNIQUE (tenant_id, execution_id, node_id, phase, call_index)
);

-- Seed: input schemas match the mocks contract. crm.delete is the inverse of crm.upsert
-- (delete-by-external_ref is naturally idempotent, so a re-call is safe: NATIVE_KEY semantics).
INSERT INTO tool_registry (tool_name, description, input_schema, output_schema, scopes, timeout_ms, retry,
                           reversibility, idempotency, compensation_tool, lookup, dry_run_example) VALUES
('payments.charge', 'Charge a customer',
 '{"type":"object","additionalProperties":false,"required":["customer_id","amount_cents","currency"],
   "properties":{"customer_id":{"type":"string","minLength":1},
                 "amount_cents":{"type":"integer","minimum":1},
                 "currency":{"type":"string","pattern":"^[A-Z]{3}$"}}}',
 '{"type":"object","required":["charge_id"],"properties":{"charge_id":{"type":"string"},"status":{"type":"string"}}}',
 '{payments:write}', 10000,
 '{"max_attempts":5,"initial_interval_ms":1000,"backoff_coefficient":2.0,"max_interval_ms":30000}',
 'COMPENSATABLE', 'NATIVE_KEY', 'payments.refund', NULL,
 '{"charge_id":"ch_dryrun","status":"succeeded"}'),
('payments.refund', 'Refund a charge',
 '{"type":"object","additionalProperties":false,"required":["charge_id"],
   "properties":{"charge_id":{"type":"string","minLength":1}}}',
 '{"type":"object","required":["refund_id"],"properties":{"refund_id":{"type":"string"},"status":{"type":"string"}}}',
 '{payments:write}', 10000,
 '{"max_attempts":10,"initial_interval_ms":1000,"backoff_coefficient":2.0,"max_interval_ms":60000}',
 'RETRIABLE', 'NATIVE_KEY', NULL, NULL,
 '{"refund_id":"re_dryrun","status":"succeeded"}'),
('messaging.send', 'Send a message to a recipient',
 '{"type":"object","additionalProperties":false,"required":["to","body"],
   "properties":{"to":{"type":"string","minLength":1},"body":{"type":"string","minLength":1}}}',
 '{"type":"object","properties":{"message_id":{"type":"string"},"status":{"type":"string"}}}',
 '{messaging:send}', 5000,
 '{"max_attempts":3,"initial_interval_ms":1000,"backoff_coefficient":2.0,"max_interval_ms":10000}',
 'PIVOT', 'NONE', NULL, NULL,
 '{"message_id":"msg_dryrun","status":"sent"}'),
('crm.upsert', 'Create or update a CRM contact keyed by external_ref',
 '{"type":"object","additionalProperties":false,"required":["external_ref","name","email"],
   "properties":{"external_ref":{"type":"string","minLength":1},"name":{"type":"string","minLength":1},
                 "email":{"type":"string","format":"email"},"label":{"type":"string"}}}',
 '{"type":"object","required":["external_ref"],"properties":{"external_ref":{"type":"string"}}}',
 '{crm:write}', 5000,
 '{"max_attempts":5,"initial_interval_ms":500,"backoff_coefficient":2.0,"max_interval_ms":10000}',
 'COMPENSATABLE', 'LOOKUP', 'crm.delete',
 '{"tool":"crm.get","args":{"external_ref":"{{args.external_ref}}"}}',
 '{"external_ref":"lead_dryrun","name":"Dry Run","email":"dry@example.com","label":"hot"}'),
('crm.delete', 'Delete a CRM contact by external_ref (inverse of crm.upsert)',
 '{"type":"object","additionalProperties":false,"required":["external_ref"],
   "properties":{"external_ref":{"type":"string","minLength":1}}}',
 '{"type":"object","properties":{"external_ref":{"type":"string"},"deleted":{"type":"boolean"}}}',
 '{crm:write}', 5000,
 '{"max_attempts":10,"initial_interval_ms":1000,"backoff_coefficient":2.0,"max_interval_ms":60000}',
 'RETRIABLE', 'NATIVE_KEY', NULL, NULL,
 '{"external_ref":"lead_dryrun","deleted":true}'),
('crm.get', 'Read a CRM contact by external_ref',
 '{"type":"object","additionalProperties":false,"required":["external_ref"],
   "properties":{"external_ref":{"type":"string","minLength":1}}}',
 '{"type":"object","properties":{"external_ref":{"type":"string"},"name":{"type":"string"},
   "email":{"type":"string"},"label":{"type":"string"}}}',
 '{crm:read}', 5000,
 '{"max_attempts":3,"initial_interval_ms":500,"backoff_coefficient":2.0,"max_interval_ms":5000}',
 'READ_ONLY', 'NONE', NULL, NULL,
 '{"external_ref":"lead_dryrun","name":"Dry Run","email":"dry@example.com","label":"hot"}'),
('leads.fetch', 'Fetch a page of leads',
 '{"type":"object","additionalProperties":false,
   "properties":{"limit":{"type":"integer","minimum":1,"maximum":100}}}',
 '{"type":"object","required":["leads"],"properties":{"leads":{"type":"array"}}}',
 '{leads:read}', 5000,
 '{"max_attempts":3,"initial_interval_ms":500,"backoff_coefficient":2.0,"max_interval_ms":5000}',
 'READ_ONLY', 'NONE', NULL, NULL,
 '{"leads":[{"external_ref":"lead_dryrun","name":"Dry Run","email":"dry@example.com"}]}');
