[versions]
spring-boot = "3.5.16"
spring-dependency-management = "1.1.7"
temporal = "1.40.0"
wiremock = "3.13.2"
archunit = "1.4.2"
json-schema-validator = "1.5.9"

[libraries]
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-docker-compose = { module = "org.springframework.boot:spring-boot-docker-compose" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }
flyway-core = { module = "org.flywaydb:flyway-core" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }
postgresql = { module = "org.postgresql:postgresql" }
micrometer-prometheus = { module = "io.micrometer:micrometer-registry-prometheus" }
temporal-sdk = { module = "io.temporal:temporal-sdk", version.ref = "temporal" }
temporal-testing = { module = "io.temporal:temporal-testing", version.ref = "temporal" }
json-schema-validator = { module = "com.networknt:json-schema-validator", version.ref = "json-schema-validator" }
testcontainers-junit = { module = "org.testcontainers:junit-jupiter" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql" }
httpclient5 = { module = "org.apache.httpcomponents.client5:httpclient5" }
wiremock = { module = "org.wiremock:wiremock-standalone", version.ref = "wiremock" }
archunit = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
